export const surpriseMePrompts = [
  'an armchair in the shape of an avocado',
  'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess',
  'panda mad scientist mixing sparkling chemicals, digital art',
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
  'an astronaut lounging in a tropical resort in space, vaporwave',
  'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'a stained glass window depicting a hamburger and french fries',
  'a pencil and watercolor drawing of a bright city in the future with flying cars',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'a painting of a fox in the style of Starry Night',
  'a bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubik’s cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A Dinosaur exploring Cape Town, photography',
  'A Man falling in Love with his Computer, digital art',
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',
  'a giraffe wearing sunglasses riding a skateboard down a rainbow road',
  'a frog sitting in a luxury spa, sipping coconut water, watercolor',
  'a futuristic library floating in the clouds, digital art',
  'an owl DJ performing in a jungle rave, vibrant neon colors',
  'a steampunk elephant with mechanical wings flying over a city',
  'a koi fish swimming through a galaxy of stars, digital painting',
  'a fantasy castle made of crystal and moonlight, concept art',
  'a cup of coffee floating in zero gravity surrounded by planets',
  'a neon city at night shaped like musical instruments',
  'a robot family having a picnic in a field of giant flowers',
  'a whale flying through the sky with hot air balloons, surrealist style',
  'a snail with a glass shell containing a miniature rainforest',
  'an enchanted forest with trees shaped like musical notes',
  'a golden retriever astronaut floating through space, retro cartoon style',
  'a magical bakery run by dragons, digital painting',
  'a jellyfish shaped like a chandelier glowing underwater',
  'a desert made entirely of crystals and mirrors, dreamlike landscape',
  'a unicorn lounging by a pool, sipping a rainbow smoothie',
  'a spaceship shaped like a pineapple flying through a wormhole',
  'an ancient temple made of ice floating on a pink ocean',
  'a surreal cafe where clouds are served in cups, pastel art',
  'a lion wearing glasses reading books in a vintage library',
  'a panda astronaut floating above Saturn’s rings, cartoon style',
  'a mushroom house in the shape of a cupcake, digital art',
  'a robot chef cooking spaghetti on the surface of Mars',
  'a city built entirely on top of giant lily pads',
  'a fox riding a unicycle through a candy forest',
  'a rainbow-colored jellyfish in a night sky full of stars',
  'a chameleon blending into a Van Gogh painting',
  'a spaceship designed like a paper origami bird',
  'a tea party hosted by aliens on a purple planet',
  'a baby dragon curled up inside a glowing lantern',
  'a village built into the shells of giant turtles',
  'a magical waterfall that flows in reverse, concept art',
  'a crystal fox standing on a floating ice island',
  'a medieval knight made entirely of glowing pixels',
  'a cyberpunk cat wearing AR glasses in Tokyo',
  'a rollercoaster made of vines through the Amazon rainforest',
  'a butterfly with stained glass wings flying over a desert',
  'a squirrel running a potion shop in a fantasy forest',
  'a pegasus made of fire flying across a stormy sky',
  'an underwater city with coral skyscrapers and fish cars',
  'a candlelit dinner between two robots in Paris',
  'a group of raccoons performing a rock concert in the woods',
  'a galaxy shaped like a flower blooming in space',
  'a chocolate mountain with rivers of caramel and candy clouds',
  'a goat on a tightrope above a canyon at sunset',
  'a treehouse shaped like a dragon, glowing at night',
  'a jellybean planet orbiting a donut sun',
  'a deer made of stars walking through the cosmos',
  'a fantasy train powered by clouds and moonlight',
  'a space whale surfing solar winds past a red dwarf star',
  'a bear writing poetry in a magical snow-covered forest',
  'an orchestra of animals playing symphonies on floating rocks',
  'a lollipop city with candy cane lamp posts and gumdrop cars',
  'a surreal mirror maze reflecting infinite versions of a rabbit',
  'a telescope looking at a moon shaped like a cat',
  'a flamingo ice skating on a frozen rainbow lake',
  'a snail pulling a wagon of stars through the night sky',
  'a futuristic observatory made of transparent water',
  'a ghost cat napping on a crescent moon',
  'a desert caravan of camels with sails like ships',
  'a tree made of water growing in the sky',
  'a mushroom growing through a vinyl record player',
  'a robot artist painting a storm with light'
];
